//Sing up
###
POST http://localhost:3977/api/v1/sign-up
Content-Type: application/json

{
    "nombre_org": "Credecoop1",
    "descripcion_org": "Solidez y confianza",
    "tipo_org": "Financiera",
    "correo_org": "crede1@gmail.com",
    "clave_org": "una"
}

//Registrar empleados
###
POST http://localhost:3977/api/v1/registrar/usuarios
Content-Type: application/json

{
    "nombre_emp": "Pedro",
    "cedula_emp": "145678890",
    "apellido1_emp": "Badilla",
    "apellido2_emp": "Arias",
    "edad_emp": 21,
    "fecNacimiento_emp": "2000-08-08"
}

###
POST http://localhost:3977/api/v1/registrar/tramites
Content-Type: application/json

{
    "tipo_tra": "Renovacion",
    "departamento_id": "3js9f3jf83hfejwrf834bf",
    "tipo_org": "Administrativa",
    "ciclo_tra":
    {
        "ciclo": {
            "nombre_cic": "Financiero",
            "estado_cic": false
        }
    }
}

###
GET http://localhost:3977/api/v1/obtener/628804d9ecd45d102aafcdb32


###
GET http://localhost:3977/api/v1/obtener


###
PUT http://localhost:3977/api/v1/actualizar/6284722a6819e4f9b4fb1b0dd
Content-Type: application/json

{
    "nombre_emp": "Reyner",
    "cedula_emp": "109283345",
    "apellido1_emp": "Badilla",
    "apellido2_emp": "Arias",
    "edad_emp": 21,
    "fecNacimiento_emp": "2000-08-08"
}

###
DELETE http://localhost:3977/api/v1/eliminar/6288594676f7807960930e60

//Sing up
###
POST http://localhost:3977/api/v1/registrar/casos
Content-Type: application/json

{
    "fecApertura_cas": "2000-08-08",
    "fecFinalizacion_cas": "2000-09-08",
    "nume_cas": 1,
    "formato_cas": "Arial",
    "isAbierto_cas": true,
    "id_tramite": "sdapdaposfmkspkp"
}