//Sing up
###
POST http://localhost:3977/api/v1/organizacion/crearOrganizacion
Content-Type: application/json

{
    "nombre_org": "Credecoop3ssss34",
    "descripcion_org": "Solidezsssdf y confianza",
    "tipo_org": "Financisssdfera",
    "correo_org": "crede2@ssgmail.sdfcom",
    "clave_org": "ussdfna"
}

//Registrar empleados
###
POST http://localhost:3977/api/v1/registrar/usuario
Content-Type: application/json

{
    "nombre_usuario": "String",
    "rol": "String",
    "contrasena": "String",
    "organizacion_id": "Object"
}

###
POST http://localhost:3977/api/v1/empleados/registrar/empleados
Content-Type: application/json

{
    "nombre_emp": "dfg",
    "apellidos_emp": "sdff",
    "cedula_emp": "jssssddddssscdddf",
    "fecNacimiento_emp": "2002-08-01",
    "tipoEmpleado": "jsdf",
    "id_departamento": "sdsdfssdfsdfpudf"
}

###

POST http://localhost:3977/api/v1/tramites/registrartramites
Content-Type: application/json

{
    "tipo_tra": "Contratacion Laboral2",
    "departamento_id":"12342",
    "tipo_org": "Banco2",
    "ciclo_tra":
    {
        "ciclo": {
            "nombre_cic": "ciclo12",
            "estado_cic": true
        }
    }
}



###
GET http://localhost:3977/api/v1/empleados/obtener/empleadosPorDepartamento/62ad57cf6bd035518908f25e

###
PUT http://localhost:3977/api/v1/actualizar/6284722a6819e4f9b4fb1b0dd
Content-Type: application/json

{
    "nombre_emp": "Reyner",
    "cedula_emp": "109283345",
    "apellido1_emp": "Badilla",
    "apellido2_emp": "Arias",
    "edad_emp": 21,
    "fecNacimiento_emp": "2000-08-08"
}

###
DELETE http://localhost:3977/api/v1/eliminar/6288594676f7807960930e60

//Usuarios

###
POST http://localhost:3977/api/v1/registrar/usuario
Content-Type: application/json

{
    "nombre_usuario": "una123",
    "rol": "Ingeniero",
    "contrasena": "una321",
    "organizacion_id": "3js9f3jf83hfejwrf834bfss"
}


###
POST http://localhost:3977/api/v1/registrar/departamento
Content-Type: application/json

{
    "nombre_dep": "String",
    "jefe_dep": "String",
    "dir_dep": "String",
    "tel_dep": 88907644,
    "correo_dep": "String"
}

###
GET http://localhost:3977/api/v1/obtener/usuario/62a55dad7e7883a2ed9f731b
Content-Type: application/json

{
    "nombre_usuario": "una123",
    "rol": "Ingeniero",
    "contrasena": "una321",
    "organizacion_id": "3js9f3jf83hfejwrf834bfss"
}
