//Sing up
###
POST http://localhost:3977/api/v1/crearOrganizacion
Content-Type: application/json

{
    "nombre_org": "Credecoop1",
    "descripcion_org": "Solidez y confianza",
    "tipo_org": "Financiera",
    "correo_org": "crede2@gmail.com",
    "clave_org": "una"
}

//Registrar empleados
###
POST http://localhost:3977/api/v1/registrar/usuario
Content-Type: application/json

{
    "nombre_usuario": "String",
    "rol": "String",
    "contrasena": "String",
    "organizacion_id": "Object"
}

###
POST http://localhost:3977/api/v1/registrar/tramites
Content-Type: application/json

{
    "tipo_tra": "Renovacion",
    "departamento_id": "3js9f3jf83hfejwrf834bf",
    "tipo_org": "Administrativa",
    "ciclo_tra":
    {
        "ciclo": {
            "nombre_cic": "Financiero",
            "estado_cic": false
        }
    }
}

###
GET http://localhost:3977/api/v1/obtener/628804d9ecd45d102aafcdb32


###
GET http://localhost:3977/api/v1/obtener

###
GET http://localhost:3977/api/v1/obtener/usuario/login/ice/345



###
PUT http://localhost:3977/api/v1/actualizar/6284722a6819e4f9b4fb1b0dd
Content-Type: application/json

{
    "nombre_emp": "Reyner",
    "cedula_emp": "109283345",
    "apellido1_emp": "Badilla",
    "apellido2_emp": "Arias",
    "edad_emp": 21,
    "fecNacimiento_emp": "2000-08-08"
}

###
DELETE http://localhost:3977/api/v1/eliminar/6288594676f7807960930e60

//Usuarios

###
POST http://localhost:3977/api/v1/registrar/usuario
Content-Type: application/json

{
    "nombre_usuario": "una123",
    "rol": "Ingeniero",
    "contrasena": "una321",
    "organizacion_id": "3js9f3jf83hfejwrf834bfss"
}


###
GET http://localhost:3977/api/v1/obtener/usuario/62a55dad7e7883a2ed9f731b